import { Indexer, MemData } from '@0gfoundation/0g-storage-ts-sdk';
import { ethers } from 'ethers';
import { readFile, writeFile } from 'node:fs/promises';

const BASE = process.env.ROUTER_BASE_URL;
const RPC = 'https://evmrpc-testnet.0g.ai';
const INDEXER = 'https://indexer-storage-testnet-turbo.0g.ai';

const baseBytes = await readFile('public/avatar-base.png');
const form = new FormData();
form.append('model', 'qwen-image-edit');
form.append('prompt', 'recolor into a warm amber glowing soul orb, keep CRT pixel style');
form.append('size', '512x512');
form.append('image', new Blob([baseBytes], { type: 'image/png' }), 'base.png');
const r = await fetch(`${BASE}/images/edits`, { method: 'POST', headers: { Authorization: `Bearer ${process.env.ROUTER_API_KEY}` }, body: form });
if (!r.ok) throw new Error(`image edit failed: ${r.status} ${await r.text()}`);
const j = await r.json();
const bytes = Buffer.from(j.data[0].b64_json, 'base64');
console.log('generated bytes:', bytes.length);

const signer = new ethers.Wallet(process.env.PRIVATE_KEY, new ethers.JsonRpcProvider(RPC));
const indexer = new Indexer(INDEXER);
const blob = new MemData(new Uint8Array(bytes));
const [tree, treeErr] = await blob.merkleTree();
if (treeErr || !tree) throw new Error(`merkleTree: ${treeErr ?? 'null tree'}`);
const rootHash = tree.rootHash();
const [, err] = await indexer.upload(blob, RPC, signer);
if (err) throw err;
console.log('uploaded rootHash:', rootHash);
const dlErr = await indexer.download(rootHash, '/tmp/smoke-avatar.png', true);
if (dlErr) throw dlErr;
await writeFile('/tmp/smoke-avatar-check.txt', 'ok');
console.log('round-trip OK');
